### ISSUE TITLE
Error with CSV and Changing units to Metric

### ISSUE THREAD

**Issue by wt9bind** [AbnormalDistributions/e_paper_weather_display#19]
Hi,

Thanks so much for building this code. I have purchased the e-Paper HAT and installed the code, but I am getting two issues:

1. Traceback (most recent call last): File "weater.py", Line 145, in <module> with open('records.csv', 'a', newline='') as csv_file: TypeError: 'newline' is an invalid keyword argument for this function and; 
2. If I change line 80 to 'Metric' it still shows Fahrenheit. Do I need to change this to Metric, then go through and change all references to 'F' to 'C'?

Thank you!

**Comment by lbewsell** [comment]
1. It looks like this may be your issue
 - https://stackoverflow.com/questions/51832593/typeerror-newline-is-an-invalid-keyword-argument-for-this-function/51833105
 - https://stackoverflow.com/questions/32811992/python3-csv-writer-failing-exiting-on-error-typeerror-newline-is-an-invalid

2. I've create a PR for Metric conversion: 
- https://github.com/AbnormalDistributions/e_paper_weather_display/pull/27 

Here is the changed file, feel free to test it, but be sure to backup the one you are using locally first. https://github.com/AbnormalDistributions/e_paper_weather_display/blob/fc880ab2fc9e2536288cb97e51989c3299c2b324/weather.py
