### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Henry-277** [AbnormalDistributions/e_paper_weather_display#23]
Hi!

I keep getting those Errors:

Traceback (most recent call last):
  File "/home/pi/Downloads/e_paper_weather_display-master/weather.py", line 12, in <module>
    from waveshare_epd import epd7in5_V2
  File "lib/waveshare_epd/epd7in5_V2.py", line 32, in <module>
    from . import epdconfig
  File "lib/waveshare_epd/epdconfig.py", line 146, in <module>
    implementation = RaspberryPi()
  File "lib/waveshare_epd/epdconfig.py", line 50, in __init__
    self.SPI = spidev.SpiDev(0, 0)
FileNotFoundError: [Errno 2] No such file or directory

Can someone help? I am a bit lost :(

**Comment by Henry-277** [comment]
When I'm running it with the console i am getting different errors:

Traceback (most recent call last):
  File "weather.py", line 234, in <module>
    write_to_screen(screen_output_file, 600)
  File "weather.py", line 34, in write_to_screen
    epd.display(epd.getbuffer(h_image))
TypeError: display() missing 1 required positional argument: 'imagered'

**Comment by AbnormalDistributions** [comment]
Make sure you have downloaded and have access to the lib/waveshare_epd directory in the repository. See if that helps. :)

**Comment by testataaaa** [comment]
I have the same issue, was this resolved?

running Raspberry Pi OS lite, copied the full folder into the main directory, and ran the weather.py.

**Comment by testataaaa** [comment]
I had the same issue as OP, solved it by setting up dependencies as follows:

sudo apt update && sudo apt upgrade  

sudo apt install git gsfonts python3 python3-pip cairosvg pigpio python3-pigpio  

sudo pip3 install python-dateutil astral spidev RPi.GPIO Pillow google-api-python-client google-auth-httplib2 google-auth-oauthlib msal

sudo sed -i s/#dtparam=spi=on/dtparam=spi=on/ /boot/config.txt 

sudo reboot
