### ISSUE TITLE
Stops Updating at 0300

### ISSUE THREAD

**Issue by pjockey** [AbnormalDistributions/e_paper_weather_display#24]
I started anew with Bullseye and reinstalled the program using Git. Updated all of the required info in weather.py and have been running the script for a bout 4 days and every morning, the last update is just before 0300. Terminal states

```
Attempting to connect to OWM.
Connection to OWM successful.
Connection to Open Weather successful.
Weather data appended to CSV.
Clearning screen to avoid burn-in. (I just see there is a spelling mistake)
```

I stop the script and and restart and off it goes. 

Is there something I should be looking at to see why the script stops at 0300?

**Comment by lbewsell** [comment]
Here are the lines in the code handling this. If you don't want this to happen comment out this block. 

https://github.com/AbnormalDistributions/e_paper_weather_display/blob/98e4061dae3f2cd2b3cb84bd268b2ee8721df490/weather.py#L228-L231
