### ISSUE TITLE
Stops Updating

### ISSUE THREAD

**Issue by pjockey** [AbnormalDistributions/e_paper_weather_display#28]
The display stops updating and it does not appear to be at any specific time. The code is still running, but the display as stopped getting the information. A quick ctrl+c and then the up arrow, enter and the code starts all over again and the display updates.

Do you have any idea what might be happening?
Thanks

**Comment by AbnormalDistributions** [comment]
I haven't had that issue. I'd recommend modifying the code so it only runs once and stops. Then set up a scheduled/cron task to have it run at a certain time. I've been meaning to do that, but I've just not had the time.
